### ISSUE TITLE
build.gradle and settings.gradle missing

### ISSUE THREAD

**Issue by nbonavia** [craiggrummitt/Notify#1]
Hi Crag,

I just wanted to inform you that anyone wanting to clone the git repo and import it in android studio will find it a bit challenging since the root folder's build.gradle and settings.gradle files are missing from the git repo.

I was able to import the files successfully after importing the following: -

build.gradle

```java
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.0.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}
```

settings.gradle
include ':app'
```java

```

**Comment by craiggrummitt** [comment]
Thanks for that Neville, how strange, I used the gitignore that Android Studio creates by default, I assumed that would be the standard. Even including the files you mentioned I had difficult importing the project so I ended up just including almost all project files. Can you have a look and confirm it's ok? I also made the change to the Umbrella project: https://github.com/craiggrummitt/Umbrella

**Comment by nbonavia** [comment]
Hi Craig,

Normally I use this .gitignore as a standard
https://github.com/github/gitignore/blob/master/Android.gitignore.

Neville.

**Comment by craiggrummitt** [comment]
Thanks Neville.
